export const metadata = {
  title: "Seller Profile | Replica",
  description: "Generated by create next app",
};

const SellerProfileLayout = ({ children }) => {
  return children;
};

export default SellerProfileLayout;
