export const metadata = {
  title: "Post Job | Replica",
  description: "Generated by create next app",
};

const PostJobLayout = ({ children }) => {
  return children;
};

export default PostJobLayout;
