import React from "react";

export const metadata = {
  title: "Login | Replica",
  description: "Generated by create next app",
};

const LoginLayout = ({ children }) => {
  return children;
};

export default LoginLayout;
