export const metadata = {
  title: "Description | Replica",
  description: "Generated by create next app",
};

const LoginLayout = ({ children }) => {
  return children;
};

export default LoginLayout;
