"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";
import CategoryBar from "@/components/CategoryBar";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

const metadata = {
  title: "Home | Replica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Navbar></Navbar>
          <CategoryBar></CategoryBar>
          <div className="min-h-[calc(100vh-188px)] container md:mx-auto my-10">
            {children}
          </div>
          <Footer></Footer>
          <Toaster />
        </QueryClientProvider>
      </body>
    </html>
  );
}
