export const metadata = {
  title: "Profile | Replica",
  description: "Generated by create next app",
};

const UserProfileLayout = ({ children }) => {
  return children;
};

export default UserProfileLayout;
