export const metadata = {
  title: "Update Job | Replica",
  description: "Generated by create next app",
};

const UpdateJobLayout = ({ children }) => {
  return children;
};

export default UpdateJobLayout;
