export const metadata = {
  title: "Registration | Replica",
  description: "Generated by create next app",
};

const RegisterLayout = ({ children }) => {
  return children;
};

export default RegisterLayout;
